### ISSUE TITLE
Problems with building the entire thing in OMNET++

### ISSUE THREAD

**Issue by savanello** [deinleinT/V2IV2Nsim#1]
Greetings,

I've been having an issue with building the framework in windows 10, the errors I get are the following. I would be really happy if anyone could help me. Thank you in advance.

![image](https://user-images.githubusercontent.com/39371173/85880002-92fd0e00-b7db-11ea-807c-52dd29530f49.png)
![image](https://user-images.githubusercontent.com/39371173/85880080-b758ea80-b7db-11ea-8e4c-b9a452835cb8.png)

**Comment by deinleinT** [comment]
Bug occured due to a character sequence in the NRRealisticChannelModel.cc file in the comment at the beginning. Modified the License-information.
