### ISSUE TITLE
Tutorial and guidelines

### ISSUE THREAD

**Issue by mahantaf** [deinleinT/V2IV2Nsim#8]
Hello contributors,

I am working on a simulation of a VANET which I have to make changes to the current simu5g simulations. I am new to Omnet++, SUMO, and Veins. I just saw this repo and found it interesting.

I wonder if you have any tutorials or courses that I can see to become on-board on these tools. Because I somehow understand what is going on between these tools but I am unable to make changes and create my own simulations.

Best

**Comment by deinleinT** [comment]
Hello,

a good start is to follow the steps described in the readme to run the example scenarios. If you new to the toolchain, I recommend to do some general OMNET tutorials to get familiar with the concepts before getting started.

If you have deeper technical questions please contact me via email --> thomas.deinlein@fau.de

I will close this issue in a few days then. 

Kind regards,
Dr.-Ing. Thomas Deinlein
